param(
    [int]$BackendStart = 8000,
    [int]$FrontendStart = 5173,
    [int]$SearchSpan = 100
)

$ErrorActionPreference = 'Stop'

function Test-PortAvailable {
    param([int]$Port)

    $listener = $null
    try {
        $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, $Port)
        $listener.Start()
        return $true
    }
    catch {
        return $false
    }
    finally {
        if ($listener) {
            $listener.Stop()
        }
    }
}

function Get-FreePort {
    param(
        [int]$Start,
        [int]$Span
    )

    foreach ($port in ($Start..($Start + $Span))) {
        if (Test-PortAvailable -Port $port) {
            return $port
        }
    }

    throw "No free TCP port found from $Start to $($Start + $Span)."
}

$backendPort = Get-FreePort -Start $BackendStart -Span $SearchSpan
$frontendPort = Get-FreePort -Start $FrontendStart -Span $SearchSpan

if ($frontendPort -eq $backendPort) {
    $frontendPort = Get-FreePort -Start ($frontendPort + 1) -Span $SearchSpan
}

$backendTarget = "http://127.0.0.1:$backendPort"
$envLocalPath = Join-Path $PSScriptRoot 'frontend/.env.local'

@(
    '# Auto-generated by web/select-dev-ports.ps1',
    "VITE_BACKEND_TARGET=$backendTarget",
    'VITE_API_BASE_URL=/api',
    ''
) | Set-Content -Path $envLocalPath -Encoding UTF8

Write-Host "Selected backend port : $backendPort"
Write-Host "Selected frontend port: $frontendPort"
Write-Host "Updated             : $envLocalPath"
Write-Host ''
Write-Host 'PowerShell startup commands:'
Write-Host "  `$env:BACKEND_PORT='$backendPort'; bash ./web/start_backend.sh"
Write-Host "  `$env:FRONTEND_PORT='$frontendPort'; bash ./web/start_frontend.sh"
Write-Host ''
Write-Host 'Direct commands:'
Write-Host "  python -m uvicorn web.backend.main:app --reload --host 0.0.0.0 --port $backendPort"
Write-Host "  npm --prefix web/frontend run dev -- --host 127.0.0.1 --port $frontendPort --strictPort"
